import React from 'react';
import { formatCurrency } from '../utils/formatters';
import { SavingsResult } from '../types/savings';
import { Download } from 'lucide-react';

interface ResultsSummaryProps {
  results: SavingsResult;
}

export const ResultsSummary: React.FC<ResultsSummaryProps> = ({ results }) => {
  const { 
    targetAmount, 
    initialAmount, 
    periodicAmount, 
    totalContributions,
    totalInterest,
    finalBalance,
    frequency,
    timelineMonths 
  } = results;

  const downloadResults = () => {
    const frequencyText = frequency.charAt(0).toUpperCase() + frequency.slice(1);
    const content = `
      Savings Goal Summary
      -------------------
      Target Amount: ₹${formatCurrency(targetAmount)}
      Initial Amount: ₹${formatCurrency(initialAmount)}
      Time Period: ${timelineMonths} months
      
      Your ${frequencyText} Contribution: ₹${formatCurrency(periodicAmount)}
      
      Final Results:
      Total Contributions: ₹${formatCurrency(totalContributions)}
      Total Interest Earned: ₹${formatCurrency(totalInterest)}
      Final Balance: ₹${formatCurrency(finalBalance)}
      
      Generated by SavingsGoal Calculator
      ${new Date().toLocaleDateString()}
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'savings-plan.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        <div className="bg-indigo-50 rounded-xl p-6">
          <h4 className="text-lg font-semibold text-indigo-800 mb-4">Required Contribution</h4>
          <div className="text-4xl font-bold text-indigo-700 mb-2">
            ₹{formatCurrency(periodicAmount)}
          </div>
          <div className="text-indigo-600">
            {frequency.charAt(0).toUpperCase() + frequency.slice(1)}
          </div>
          <div className="mt-4 text-sm text-indigo-600">
            Save this amount {frequency} for {timelineMonths} months to reach your goal.
          </div>
        </div>
        
        <div className="bg-emerald-50 rounded-xl p-6">
          <h4 className="text-lg font-semibold text-emerald-800 mb-4">Final Results</h4>
          <div className="text-4xl font-bold text-emerald-700 mb-2">
            ₹{formatCurrency(finalBalance)}
          </div>
          <div className="text-emerald-600">Total Savings</div>
          <div className="mt-4 text-sm text-emerald-600">
            Including ₹{formatCurrency(totalInterest)} in interest earnings
          </div>
        </div>
      </div>
      
      <div className="bg-gray-50 rounded-xl p-6 mb-8">
        <h4 className="text-lg font-semibold text-gray-800 mb-4">Breakdown</h4>
        <div className="space-y-3">
          <div className="flex justify-between items-center">
            <span className="text-gray-600">Target Amount:</span>
            <span className="font-medium">₹{formatCurrency(targetAmount)}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-gray-600">Initial Amount:</span>
            <span className="font-medium">₹{formatCurrency(initialAmount)}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-gray-600">Your Contributions:</span>
            <span className="font-medium">₹{formatCurrency(totalContributions)}</span>
          </div>
          <div className="flex justify-between items-center">
            <span className="text-gray-600">Interest Earned:</span>
            <span className="font-medium text-emerald-600">₹{formatCurrency(totalInterest)}</span>
          </div>
          <div className="border-t border-gray-200 pt-2 mt-2 flex justify-between items-center">
            <span className="text-gray-600 font-semibold">Final Balance:</span>
            <span className="font-bold text-lg">₹{formatCurrency(finalBalance)}</span>
          </div>
        </div>
      </div>
      
      <div className="flex flex-wrap gap-4">
        <button 
          onClick={downloadResults}
          className="flex items-center gap-2 py-2 px-4 bg-white border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
        >
          <Download size={18} />
          Download Plan
        </button>
     
      </div>
    </div>
  );
};